### ISSUE TITLE
Cannot read property 'inArray' of undefined

### ISSUE THREAD

**Issue by alexantr** [pawelczak/EasyAutocomplete#247]
jQuery in WordPress running in noConflict mode and this script not working with WP sites.

**Comment by mickaelperrin** [comment]
Resolved by englobing the whole core file in `function($)`.

So, move line https://github.com/pawelczak/EasyAutocomplete/blob/master/src/core.js#L750 on top of file.

**Comment by toastyghost** [comment]
I moved that line to the very top of the file and successfully rebuilt with Grunt, but the problem persists. Any further insight would be appreciated.

**Comment by nikhilnagpal123** [comment]
open jQuery.easy-autocomlete.min.js in text-editor and just find "$" and replace it with "jQuery", then you might also need to replace back "jQuery1" to "$1",   it worked for me

**Comment by matthewandrews** [comment]
I found a couple of cases where $ is used in regexes (not just $1) ... so better to manually go through and find/replace each case (there are only about 15).

**Comment by quangpro1610** [comment]
> @toastyghost amazing, I loved the fix you found... Saved my life.

me too ❤️

**Comment by grohart** [comment]
Writting the following line on top of my main script did the trick for me

`window.$ = window.jQuery;
`

**Comment by matichek** [comment]
> Writting the following line on top of my main script did the trick for me
> 
> `window.$ = window.jQuery; `

Hi, this works nicely. This was the fix for using autocomplete on backend on wordpress. Thanks @grohart  👍
